apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    type: testing
    owner: operations                           # Label 'owner' should be added
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: non-violated-pod
  name: non-violated-pod
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: non-violated-pod
  template:
    metadata:
      labels:
        app: non-violated-pod
    spec:
      volumes:
      - name: temp-storage
        hostPath:
          path: /etc                              # Should not be root
      # hostIPC: true                             # Should be disabled
      # hostPID: true                             # Should be disabled
      containers:
      - image: gcr.io/google-containers/nginx
        name: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: temp-storage
          mountPath: /data
        securityContext:                      
        #   privileged: true                      # Should be disabled
          runAsUser: 1000                         # Should not be 0
          runAsGroup: 1000                        # Should not be 0
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
