apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SecureNamespace
metadata:
  name: ns-must-have-owner
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
        excludedNamespaces: ["default"]
  parameters:
    labels: ["owner"]